In [100]:
import json
import pandas as pd
import streamlit as st
import openai
from pyspark.sql import SparkSession
from langchain.chat_models import AzureChatOpenAI
from langchain.agents import create_pandas_dataframe_agent

In [51]:
spark = SparkSession.builder.appName("StreamlitDemo").getOrCreate()

In [101]:
# Open the json file
with open('raw_data/raw_data.json') as f:
    # Load the json object as a dictionary
    data = json.load(f)

In [102]:
df = pd.DataFrame(data['value'])

In [103]:
df

,Version___ID,Version___VERSION,Version___CATEGORY,Version___CURRENCY_CONVERSION_CATEGORY,Version___RATE_VERSION,Version___dataLockingOwner,Version___StartDate,Version___EndDate,Version___NumberOfPeriods,Version___Description,...,SAP_ALL_PROFITCENTER___Segment,SAP_ALL_PROFITCENTER___Department,SAP_ALL_PROFITCENTER___Row_Source,SAP_ALL_PROFITCENTER___Description,SAP_ALL_FUNCTIONALAREA___ID,SAP_ALL_FUNCTIONALAREA___Row_Source,SAP_ALL_FUNCTIONALAREA___Description,SAP_ALL_TRADINGPARTNER___ID,SAP_ALL_TRADINGPARTNER___Description,AMOUNT
0,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_A,,S4HC,Consulting Unit A,#,,Unassigned,#,Unassigned,-11000.0
1,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_A,,S4HC,Bike Parts,#,,Unassigned,#,Unassigned,181400.0
2,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_B,,S4HC,Bicycles,#,,Unassigned,#,Unassigned,14150.0
3,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_C,,S4HC,Shared Services,#,,Unassigned,#,Unassigned,-33000.0
4,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_C,,S4HC,Trading Goods,#,,Unassigned,#,Unassigned,-50000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3945,public.Plan,Plan,Planning,Planning,,,202301,202312,12,Plan,...,,,SAC,Unassigned,#,,Unassigned,#,Unassigned,3.0
3946,public.Plan,Plan,Planning,Planning,,,202301,202312,12,Plan,...,,,SAC,Unassigned,#,,Unassigned,#,Unassigned,3.0
3947,public.Plan,Plan,Planning,Planning,,,202301,202312,12,Plan,...,,,SAC,Unassigned,#,,Unassigned,#,Unassigned,3.0
3948,public.Plan,Plan,Planning,Planning,,,202301,202312,12,Plan,...,,,SAC,Unassigned,#,,Unassigned,#,Unassigned,3.0
3949,public.Plan,Plan,Planning,Planning,,,202301,202312,12,Plan,...,,,SAC,Unassigned,#,,Unassigned,#,Unassigned,3.0

In [99]:
df[df["Date___FISCAL_CALPERIOD"]=='202201']

,Version___ID,Version___VERSION,Version___CATEGORY,Version___CURRENCY_CONVERSION_CATEGORY,Version___RATE_VERSION,Version___dataLockingOwner,Version___StartDate,Version___EndDate,Version___NumberOfPeriods,Version___Description,...,SAP_ALL_PROFITCENTER___Segment,SAP_ALL_PROFITCENTER___Department,SAP_ALL_PROFITCENTER___Row_Source,SAP_ALL_PROFITCENTER___Description,SAP_ALL_FUNCTIONALAREA___ID,SAP_ALL_FUNCTIONALAREA___Row_Source,SAP_ALL_FUNCTIONALAREA___Description,SAP_ALL_TRADINGPARTNER___ID,SAP_ALL_TRADINGPARTNER___Description,AMOUNT
0,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_A,,S4HC,Consulting Unit A,#,,Unassigned,#,Unassigned,-11000.0
1,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_A,,S4HC,Bike Parts,#,,Unassigned,#,Unassigned,181400.0
2,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_B,,S4HC,Bicycles,#,,Unassigned,#,Unassigned,14150.0
3,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_C,,S4HC,Shared Services,#,,Unassigned,#,Unassigned,-33000.0
4,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_C,,S4HC,Trading Goods,#,,Unassigned,#,Unassigned,-50000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_A,,S4HC,Bike Parts,YB20,,Production,#,Unassigned,0.0
321,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_B,,S4HC,Bicycles,YB20,,Production,#,Unassigned,0.0
322,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_A,,S4HC,Bike Parts,YB20,,Production,#,Unassigned,0.0
323,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_B,,S4HC,Bicycles,YB20,,Production,#,Unassigned,0.0
324,public.Actual,Actual,Actuals,Actuals,,,202201,202212,,Actual,...,1000_C,,S4HC,Shared Services,YB30,,Sales and Distribution,#,Unassigned,0.0

In [89]:
df = pd.DataFrame(df['Version___Description'],df["Date___FISCAL_CALPERIOD"],df['FLOW_TYPE___Description'],df["SAP_ALL_COMPANY_CODE___Description"],df["SAP_FI_IFP_GLACCOUNT___Description"],df["SAP_ALL_PROFITCENTER___Description"],df["SAP_ALL_FUNCTIONALAREA___Description"],df["SAP_ALL_TRADINGPARTNER___Description"],df["AMOUNT"])

KeyError: 'Version___Description'

In [87]:
df = df.dropna()

In [88]:
df

Empty DataFrame
Columns: [Version___ID]
Index: []

In [7]:
def _get_col_dtype(col):
    """
    Infer datatype of a pandas column, process only if the column dtype is object.
    input: col: a pandas Series representing a df column.
    """
    if col.dtype == "object":
        # try numeric
        try:
            col_new = pd.to_datetime(col.dropna().unique())
            return col_new.dtype
        except:
            try:
                col_new = pd.to_numeric(col.dropna().unique())
                return col_new.dtype
            except:
                try:
                    col_new = pd.to_timedelta(col.dropna().unique())
                    return col_new.dtype
                except:
                    return "object"
    else:
        return col.dtype

In [8]:
df = df.replace("", "0")

In [9]:
df = df.astype({col: _get_col_dtype(df[col]) for col in df.columns})

In [10]:
#OPENAI_DEPLOYMENT_NAME=#
#OPENAI_MODEL_NAME=#
#OPENAI_DEPLOYMENT_BASE=#
#OPENAI_DEPLOYMENT_VERSION=#
OPENAI_API_KEY= '57e7b0f37d0f4dc1b657496a726156c0'

In [11]:
chat = AzureChatOpenAI(deployment_name="sapaicx_gpt35",
                      model_name="gpt-35-turbo",
                      openai_api_base="https://openai-sapaicx-canada.openai.azure.com/",
                      openai_api_version="2023-03-15-preview",
                      openai_api_key=OPENAI_API_KEY,
                      openai_api_type="azure")

In [12]:
chat

AzureChatOpenAI(cache=None, verbose=False, callbacks=None, callback_manager=None, tags=None, metadata=None, client=<class 'openai.api_resources.chat_completion.ChatCompletion'>, model_name='gpt-35-turbo', temperature=0.7, model_kwargs={}, openai_api_key='57e7b0f37d0f4dc1b657496a726156c0', openai_api_base='https://openai-sapaicx-canada.openai.azure.com/', openai_organization='', openai_proxy='', request_timeout=None, max_retries=6, streaming=False, n=1, max_tokens=None, tiktoken_model_name=None, deployment_name='sapaicx_gpt35', openai_api_type='azure', openai_api_version='2023-03-15-preview')

In [13]:
print(str(df.describe(include='all')))

         Version___ID Version___VERSION Version___CATEGORY  \
count            3949              3949               3949
unique              2                 2                  2
top     public.Actual            Actual            Actuals
freq             3921              3921               3921
first             NaN               NaN                NaN
last              NaN               NaN                NaN
mean              NaN               NaN                NaN
std               NaN               NaN                NaN
min               NaN               NaN                NaN
25%               NaN               NaN                NaN
50%               NaN               NaN                NaN
75%               NaN               NaN                NaN
max               NaN               NaN                NaN

       Version___CURRENCY_CONVERSION_CATEGORY  Version___RATE_VERSION  \
count                                    3949                  3949.0
unique                                      2                     NaN
top                                   Actuals                     NaN
freq                                     3921                     NaN
first                                     NaN                     NaN
last                                      NaN                     NaN
mean                                      NaN                     0.0
std                                       NaN                     0.0
min                                       NaN                     0.0
25%                                       NaN                     0.0
50%                                       NaN                     0.0
75%                                       NaN                     0.0
max                                       NaN                     0.0

        Version___dataLockingOwner  Version___StartDate  Version___EndDate  \
count                       3949.0           3949.00000         3949.00000
unique                         NaN                  NaN                NaN
top                            NaN                  NaN                NaN
freq                           NaN                  NaN                NaN
first                          NaN                  NaN                NaN
last                           NaN                  NaN                NaN
mean                           0.0         202201.70904       202212.70904
std                            0.0              8.39161            8.39161
min                            0.0         202201.00000       202212.00000
25%                            0.0         202201.00000       202212.00000
50%                            0.0         202201.00000       202212.00000
75%                            0.0         202201.00000       202212.00000
max                            0.0         202301.00000       202312.00000

        Version___NumberOfPeriods Version___Description  ...  \
count                 3949.000000                  3949  ...
unique                        NaN                     2  ...
top                           NaN                Actual  ...
freq                          NaN                  3921  ...
first                         NaN                   NaN  ...
last                          NaN                   NaN  ...
mean                     0.085085                   NaN  ...
std                      1.006993                   NaN  ...
min                      0.000000                   NaN  ...
25%                      0.000000                   NaN  ...
50%                      0.000000                   NaN  ...
75%                      0.000000                   NaN  ...
max                     12.000000                   NaN  ...

       SAP_ALL_PROFITCENTER___Segment SAP_ALL_PROFITCENTER___Department  \
count                            3949                            3949.0
unique                              4                               NaN
top                            1000_A                               NaN
freq                             1691                               NaN
first                             NaN                               NaN
last                              NaN                               NaN
mean                              NaN                               0.0
std                               NaN                               0.0
min                               NaN                               0.0
25%                               NaN                               0.0
50%                               NaN                               0.0
75%                               NaN                               0.0
max                               NaN                               0.0

        SAP_ALL_PROFITCENTER___Row_Source  SAP_ALL_PROFITCENTER___Description  \
count                                3949                                3949
unique                                  2                                   7
top                                  S4HC                            Bicycles
freq                                 3921                                1596
first                                 NaN                                 NaN
last                                  NaN                                 NaN
mean                                  NaN                                 NaN
std                                   NaN                                 NaN
min                                   NaN                                 NaN
25%                                   NaN                                 NaN
50%                                   NaN                                 NaN
75%                                   NaN                                 NaN
max                                   NaN                                 NaN

        SAP_ALL_FUNCTIONALAREA___ID SAP_ALL_FUNCTIONALAREA___Row_Source  \
count                          3949                              3949.0
unique                            8                                 NaN
top                               #                                 NaN
freq                           1885                                 NaN
first                           NaN                                 NaN
last                            NaN                                 NaN
mean                            NaN                                 0.0
std                             NaN                                 0.0
min                             NaN                                 0.0
25%                             NaN                                 0.0
50%                             NaN                                 0.0
75%                             NaN                                 0.0
max                             NaN                                 0.0

       SAP_ALL_FUNCTIONALAREA___Description SAP_ALL_TRADINGPARTNER___ID  \
count                                  3949                        3949
unique                                    8                           2
top                              Unassigned                           #
freq                                   1885                        3361
first                                   NaN                         NaN
last                                    NaN                         NaN
mean                                    NaN                         NaN
std                                     NaN                         NaN
min                                     NaN                         NaN
25%                                     NaN                         NaN
50%                                     NaN                         NaN
75%                                     NaN                         NaN
max                                     NaN                         NaN

       SAP_ALL_TRADINGPARTNER___Description        AMOUNT
count                                  3949  3.949000e+03
unique                                    2           NaN
top                              Unassigned           NaN
freq                                   3361           NaN
first                                   NaN           NaN
last                                    NaN           NaN
mean                                    NaN  4.956394e+02
std                                     NaN  5.158476e+05
min                                     NaN -3.600000e+06
25%                                     NaN -2.000000e+04
50%                                     NaN  5.000000e+03
75%                                     NaN  5.725000e+04
max                                     NaN  3.846800e+06

[13 rows x 59 columns]

C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\2687428536.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  print(str(df.describe(include='all')))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\2687428536.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  print(str(df.describe(include='all')))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\2687428536.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  print(str(df.describe(include='all')))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\2687428536.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  print(str(df.describe(include='all')))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\2687428536.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  print(str(df.describe(include='all')))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\2687428536.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  print(str(df.describe(include='all')))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\2687428536.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  print(str(df.describe(include='all')))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\2687428536.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  print(str(df.describe(include='all')))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\2687428536.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  print(str(df.describe(include='all')))

In [14]:
pd_agent = create_pandas_dataframe_agent(chat, df, verbose=True)

In [15]:
datetime_is_numeric=True

In [16]:
schema = str(df.describe(include='all'))

C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\1133562454.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  schema = str(df.describe(include='all'))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\1133562454.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  schema = str(df.describe(include='all'))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\1133562454.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  schema = str(df.describe(include='all'))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\1133562454.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  schema = str(df.describe(include='all'))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\1133562454.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  schema = str(df.describe(include='all'))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\1133562454.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  schema = str(df.describe(include='all'))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\1133562454.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  schema = str(df.describe(include='all'))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\1133562454.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  schema = str(df.describe(include='all'))
C:\Users\abhishek.cw.gupta\AppData\Local\Temp\ipykernel_5940\1133562454.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  schema = str(df.describe(include='all'))

In [30]:
len(schema)

9033

In [31]:
schema=schema[1:3000]

In [32]:
prompt = f"""
Answer the question Below by referring to the column wise description of the dataframe in question.
    Question: Calculate the variance percentage between actual and plan for column Version___VERSION for the year 2022 and 2023?

    DataFrame Description: {schema}
"""

In [25]:
prompt1= f"""
Answer the question Below by referring to the column wise description of the dataframe in question.
    Question: What is the total for AMOUNT column ?
    
    DataFrame Description: {schema}
"""

In [33]:
#pd_agent.run("variance % between actual and plan for column Version___VERSION for the year 2022 and 2023?")
try:
    pd_agent.run(prompt)
except Exception as e:
    print(e)

> Entering new  chain...
Thought: To calculate the variance percentage between actual and plan for column Version___VERSION, we need to find the actual and plan values for the year 2022 and 2023.

Action: Filter the dataframe to include only the rows where the year is 2022 or 2023.

Action Input: `df_filtered = df[(df['Date___YEAR'] == 2022) | (df['Date___YEAR'] == 2023)]`

Observation: Filter the dataframe to include only the rows where the year is 2022 or 2023. is not a valid tool, try another one.
Thought:I need to use the pandas library to filter the dataframe.
Action: Use the pandas `query` method to filter the dataframe.

Action Input: `df_filtered = df.query("Date___YEAR == 2022 | Date___YEAR == 2023")`

Observation: Use the pandas `query` method to filter the dataframe. is not a valid tool, try another one.
Thought:I can also use boolean indexing to filter the dataframe.
Action: Use boolean indexing to filter the dataframe.

Action Input: `df_filtered = df[(df['Date___YEAR'] == 2022) | (df['Date___YEAR'] == 2023)]`

Observation: Use boolean indexing to filter the dataframe. is not a valid tool, try another one.
Thought:I can use the pandas `loc` method to filter the dataframe.
Action: Use the pandas `loc` method to filter the dataframe.

Action Input: `df_filtered = df.loc[(df['Date___YEAR'] == 2022) | (df['Date___YEAR'] == 2023)]`

Observation: Use the pandas `loc` method to filter the dataframe. is not a valid tool, try another one.
Thought:I can use the pandas `query` method to filter the dataframe.
Action: Use the pandas `query` method to filter the dataframe.

Action Input: `df_filtered = df.query("Date___YEAR == 2022 | Date___YEAR == 2023")`

Observation: Use the pandas `query` method to filter the dataframe. is not a valid tool, try another one.
Thought:I can use the pandas `isin` method to filter the dataframe.
Action: Use the pandas `isin` method to filter the dataframe.

Action Input: `df_filtered = df[df['Date___YEAR'].isin([2022, 2023])]`

Observation: Use the pandas `isin` method to filter the dataframe. is not a valid tool, try another one.
Thought:I can use the pandas `query` method to filter the dataframe.
Action: Use the pandas `query` method to filter the dataframe.

Action Input: `df_filtered = df.query("Date___YEAR == 2022 | Date___YEAR == 2023")`

Observation: Use the pandas `query` method to filter the dataframe. is not a valid tool, try another one.
Thought:I need to use the pandas `loc` method to filter the dataframe.
Action: Use the pandas `loc` method to filter the dataframe.

Action Input: `df_filtered = df.loc[(df['Date___YEAR'] == 2022) | (df['Date___YEAR'] == 2023)]`

Observation: Use the pandas `loc` method to filter the dataframe. is not a valid tool, try another one.
Thought:I can use the pandas `isin` method to filter the dataframe.
Action: Use the pandas `isin` method to filter the dataframe.

Action Input: `df_filtered = df[df['Date___YEAR'].isin([2022, 2023])]`

Observation: Use the pandas `isin` method to filter the dataframe. is not a valid tool, try another one.
Thought:I can use boolean indexing to filter the dataframe.
Action: Use boolean indexing to filter the dataframe.

Action Input: `df
Observation: Use boolean indexing to filter the dataframe. is not a valid tool, try another one.
Thought:This model's maximum context length is 4096 tokens. However, your messages resulted in 4119 tokens. Please reduce the length of the messages.

In [19]:
prompt = f"""
Answer the question Below by referring to the column wise description of the dataframe in question.
    Question: What were the main drivers of cost increases in 2022

    DataFrame Description: {schema}
"""

In [20]:
prompt

'\nAnswer the question Below by referring to the column wise description of the dataframe in question.\n    Question: What were the main drivers of cost increases in 2022\n\n    DataFrame Description:          Version___ID Version___VERSION Version___CATEGORY  \\\ncount            3949              3949               3949   \nunique              2                 2                  2   \ntop     public.Actual            Actual            Actuals   \nfreq             3921              3921               3921   \nfirst             NaN               NaN                NaN   \nlast              NaN               NaN                NaN   \nmean              NaN               NaN                NaN   \nstd               NaN               NaN                NaN   \nmin               NaN               NaN                NaN   \n25%               NaN               NaN                NaN   \n50%               NaN               NaN                NaN   \n75%               NaN               NaN                NaN   \nmax               NaN               NaN                NaN   \n\n       Version___CURRENCY_CONVERSION_CATEGORY  Version___RATE_VERSION  \\\ncount                                    3949                  3949.0   \nunique                                      2                     NaN   \ntop                                   Actuals                     NaN   \nfreq                                     3921                     NaN   \nfirst                                     NaN                     NaN   \nlast                                      NaN                     NaN   \nmean                                      NaN                     0.0   \nstd                                       NaN                     0.0   \nmin                                       NaN                     0.0   \n25%                                       NaN                     0.0   \n50%                                       NaN                     0.0   \n75%                                       NaN                     0.0   \nmax                                       NaN                     0.0   \n\n        Version___dataLockingOwner  Version___StartDate  Version___EndDate  \\\ncount                       3949.0           3949.00000         3949.00000   \nunique                         NaN                  NaN                NaN   \ntop                            NaN                  NaN                NaN   \nfreq                           NaN                  NaN                NaN   \nfirst                          NaN                  NaN                NaN   \nlast                           NaN                  NaN                NaN   \nmean                           0.0         202201.70904       202212.70904   \nstd                            0.0              8.39161            8.39161   \nmin                            0.0         202201.00000       202212.00000   \n25%                            0.0         202201.00000       202212.00000   \n50%                            0.0         202201.00000       202212.00000   \n75%                            0.0         202201.00000       202212.00000   \nmax                            0.0         202301.00000       202312.00000   \n\n        Version___NumberOfPeriods Version___Description  ...  \\\ncount                 3949.000000                  3949  ...   \nunique                        NaN                     2  ...   \ntop                           NaN                Actual  ...   \nfreq                          NaN                  3921  ...   \nfirst                         NaN                   NaN  ...   \nlast                          NaN                   NaN  ...   \nmean                     0.085085                   NaN  ...   \nstd                      1.006993                   NaN  ...   \nmin                      0.000000                   NaN  ...   \n25%                      0.000000                   NaN  ...   \n50%                      0.000000                   NaN  ...   \n75%                      0.000000                   NaN  ...   \nmax                     12.000000                   NaN  ...   \n\n       SAP_ALL_PROFITCENTER___Segment SAP_ALL_PROFITCENTER___Department  \\\ncount                            3949                            3949.0   \nunique                              4                               NaN   \ntop                            1000_A                               NaN   \nfreq                             1691                               NaN   \nfirst                             NaN                               NaN   \nlast                              NaN                               NaN   \nmean                              NaN                               0.0   \nstd                               NaN                               0.0   \nmin                               NaN                               0.0   \n25%                               NaN                               0.0   \n50%                               NaN                               0.0   \n75%                               NaN                               0.0   \nmax                               NaN                               0.0   \n\n        SAP_ALL_PROFITCENTER___Row_Source  SAP_ALL_PROFITCENTER___Description  \\\ncount                                3949                                3949   \nunique                                  2                                   7   \ntop                                  S4HC                            Bicycles   \nfreq                                 3921                                1596   \nfirst                                 NaN                                 NaN   \nlast                                  NaN                                 NaN   \nmean                                  NaN                                 NaN   \nstd                                   NaN                                 NaN   \nmin                                   NaN                                 NaN   \n25%                                   NaN                                 NaN   \n50%                                   NaN                                 NaN   \n75%                                   NaN                                 NaN   \nmax                                   NaN                                 NaN   \n\n        SAP_ALL_FUNCTIONALAREA___ID SAP_ALL_FUNCTIONALAREA___Row_Source  \\\ncount                          3949                              3949.0   \nunique                            8                                 NaN   \ntop                               #                                 NaN   \nfreq                           1885                                 NaN   \nfirst                           NaN                                 NaN   \nlast                            NaN                                 NaN   \nmean                            NaN                                 0.0   \nstd                             NaN                                 0.0   \nmin                             NaN                                 0.0   \n25%                             NaN                                 0.0   \n50%                             NaN                                 0.0   \n75%                             NaN                                 0.0   \nmax                             NaN                                 0.0   \n\n       SAP_ALL_FUNCTIONALAREA___Description SAP_ALL_TRADINGPARTNER___ID  \\\ncount                                  3949                        3949   \nunique                                    8                           2   \ntop                              Unassigned                           #   \nfreq                                   1885                        3361   \nfirst                                   NaN                         NaN   \nlast                                    NaN                         NaN   \nmean                                    NaN                         NaN   \nstd                                     NaN                         NaN   \nmin                                     NaN                         NaN   \n25%                                     NaN                         NaN   \n50%                                     NaN                         NaN   \n75%                                     NaN                         NaN   \nmax                                     NaN                         NaN   \n\n       SAP_ALL_TRADINGPARTNER___Description        AMOUNT  \ncount                                  3949  3.949000e+03  \nunique                                    2           NaN  \ntop                              Unassigned           NaN  \nfreq                                   3361           NaN  \nfirst                                   NaN           NaN  \nlast                                    NaN           NaN  \nmean                                    NaN  4.956394e+02  \nstd                                     NaN  5.158476e+05  \nmin                                     NaN -3.600000e+06  \n25%                                     NaN -2.000000e+04  \n50%                                     NaN  5.000000e+03  \n75%                                     NaN  5.725000e+04  \nmax                                     NaN  3.846800e+06  \n\n[13 rows x 59 columns]\n'

In [21]:
#pd_agent.run("variance % between actual and plan for column Version___VERSION for the year 2022 and 2023?")
try:
    pd_agent.run(prompt)
except Exception as e:
    print(e)

> Entering new  chain...
Could not parse LLM output: `Thought: To answer the question, I need to identify the column that represents cost`